#!/usr/bin/env node
/**
 * FaceVault KYC Plugin — Build Script (v2 / hosted-page mode)
 *
 * Two output flavors:
 *
 *  1. Generic template (default) — `facevault-kyc.json` with a placeholder
 *     slug in the bundle URL. Real per-operator JSONs are generated by the
 *     FaceVault dashboard (GET /api/v1/kyc-sites/{site_id}/integrations/
 *     hollaex.json), which bakes slug + origins directly into web_view[0].
 *     meta. Operators are told to download from the dashboard, not from
 *     this generic file.
 *
 *  2. Marketplace template (--marketplace) — `facevault-kyc.marketplace.json`
 *     with top-level `public_meta.slug` as a HollaEx-configurable field.
 *     Operator installs from the HollaEx App Store, then types their slug
 *     into the plugin Configure dialog. Submit this shape to the HollaEx
 *     marketplace; the dashboard download path is for everyone else.
 *
 * Usage:
 *   node build.js                # generic template
 *   node build.js --marketplace  # marketplace template
 *   node build.js --minify       # minified output
 */

const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const minify = process.argv.includes('--minify');
const marketplace = process.argv.includes('--marketplace');

// Read semver from package.json so the JSON output records exactly which
// plugin version produced it. The webview reads this back from
// web_view[0].meta.installed_version and compares against the manifest
// served by api.facevault.id to decide whether to show the upgrade banner.
const PKG_VERSION = JSON.parse(
	fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8')
).version;

const WEBVIEW_BUNDLE_BASE = 'https://facevault.id/plugins/facevault-kyc-view.js';
// Cache-buster version. Bump when the webview bundle changes so HollaEx kits
// re-fetch instead of serving the CF-cached prior bundle.
const BUNDLE_VERSION = 8;
// Sentinel slug that the webview detects and renders as "plugin not configured"
// — same UX as missing slug, since the bundle treats placeholder as "no slug
// available." Keeps the generic template safely non-functional.
const PLACEHOLDER_SLUG = 'configure-via-dashboard';

// HollaEx kit injects the webview into the user-facing KYC tab only when
// is_verification_tab + type: 'home' live inside web_view[0].meta. At the
// root of the entry they're ignored and HollaEx renders the "under
// construction" placeholder. (Same regression that hit v1.0.0.)
const SHIELD_SVG_B64 = Buffer.from(
	'<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/><path d="M9 12l2 2 4-4"/></svg>'
).toString('base64');

// HollaEx kit's `Image` component (web/src/components/Image/index.js)
// decides inline SVG vs <img> rendering via `icon.indexOf('.svg') > 0`.
// A plain `data:image/svg+xml;base64,...` URL fails that check and falls
// through to <img>, which renders base64-encoded SVG unreliably across
// browsers/CSP settings — the tab strip then shows a blank slot instead
// of our shield. Appending `#shield.svg` is a URL fragment ignored by
// the data-URL parser, but it makes the kit's substring check pass so
// ReactSVG inlines our icon properly.
const SHIELD_ICON_DATA_URL = 'data:image/svg+xml;base64,' + SHIELD_SVG_B64 + '#shield.svg';

// Top-level `public_meta` schema for the marketplace template. HollaEx's
// Plugins → Configure UI renders inputs from this; the operator-typed value
// lands at `enabledPlugins[].public_meta.slug.value` (or `.slug` flat,
// depending on kit version). The bundle accepts either shape.
//
// Slug only — keeps the Configure UI to one field for non-technical operators.
// Self-hosted FaceVault deployments (rare) edit web_view[0].meta directly in
// the JSON for hosted_base/api_base overrides.
const MARKETPLACE_PUBLIC_META = {
	slug: {
		type: 'string',
		required: true,
		description:
			'Your FaceVault hosted-page slug (e.g. "acme"). Sign up at devdash.facevault.id, ' +
			'create a hosted-verification site, and paste the slug here.',
		value: '',
	},
};

// Top-level `type` is the plugin category. HollaEx kit maps it into
// `enabledPlugins` and uses it to decide which built-in verification tabs to
// show (web/src/containers/Verification/index.js — values 'kyc', 'bank',
// 'sms', 'user_payments' trigger the stock built-in tabs). We deliberately
// use 'external_kyc' so the stock identity tab — which renders as "page
// under construction" alongside our plugin tab — does NOT appear. Admin
// auto-detect of "the kyc plugin" falls back to name 'kyc' but its server
// routes are 405 on Cloud anyway and we ship no server.js.
const plugin = {
	name: 'facevault-kyc',
	version: 1,
	type: 'external_kyc',
	author: 'FaceVault',
	bio: 'AI-powered identity verification.',
	description: marketplace
		? 'Identity verification powered by FaceVault. Face matching, document OCR, ' +
		  'liveness detection, and anti-spoofing — runs on FaceVault\'s branded hosted page; ' +
		  'works on HollaEx Cloud and self-hosted kits. After install, set your slug in Configure.'
		: 'Identity verification powered by FaceVault. Face matching, document OCR, ' +
		  'liveness detection, and anti-spoofing — no manual review queue. ' +
		  'NOTE: install the per-operator JSON from your FaceVault dashboard, not this generic template.',
	documentation: 'https://facevault.id/docs',
	logo: 'https://facevault.id/logo-shield.png',
	icon: 'https://facevault.id/favicon.svg',
	url: 'https://facevault.id',
	meta: {},
	public_meta: marketplace ? MARKETPLACE_PUBLIC_META : {},
	prescript: { install: [], run: null },
	postscript: { run: null },
	web_view: [
		{
			// Marketplace bundle URL has no slug query — bundle reads it from
			// public_meta at runtime. Generic template keeps the placeholder
			// slug for self-hosted <script>-tag setups.
			src: marketplace
				? WEBVIEW_BUNDLE_BASE + '?v=' + BUNDLE_VERSION
				: WEBVIEW_BUNDLE_BASE + '?slug=' + PLACEHOLDER_SLUG + '&v=' + BUNDLE_VERSION,
			meta: {
				is_verification_tab: true,
				type: 'home',
				// Plugin semver, used by the webview to decide whether to
				// prompt admins about a newer release. Compared against
				// /api/v1/integrations/hollaex/manifest's latest_version.
				installed_version: PKG_VERSION,
				// `string.id` and `icon.id` are LOOKUP KEYS the kit globalizes
				// (utils/id.js → generateGlobalId) and dereferences against
				// the in-app STRINGS / ICONS registries. The actual text and
				// icon data must be supplied via `strings` and `icons` below
				// — `string.value` / `icon.value` are NOT read by the kit.
				string: { id: 'FACEVAULT_KYC_VERIFICATION' },
				icon: { id: 'FACEVAULT_SHIELD_ICON' },
				strings: {
					en: { FACEVAULT_KYC_VERIFICATION: 'Identity Verification' },
				},
				icons: {
					dark: { FACEVAULT_SHIELD_ICON: SHIELD_ICON_DATA_URL },
					white: { FACEVAULT_SHIELD_ICON: SHIELD_ICON_DATA_URL },
				},
			},
		},
	],
	admin_view: null,
};

const outFile = path.join(
	ROOT,
	marketplace ? 'facevault-kyc.marketplace.json' : 'facevault-kyc.json'
);
const output = minify ? JSON.stringify(plugin) : JSON.stringify(plugin, null, 2);
fs.writeFileSync(outFile, output);
const size = (Buffer.byteLength(output) / 1024).toFixed(1);
console.log('Built: ' + outFile + ' (' + size + ' KB)');
